services:
  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: mysql_user_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234 # root password
      MYSQL_DATABASE: user_db # auto-create database
      MYSQL_USER: myuser # optional custom user
      MYSQL_PASSWORD: 1234 # user password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql # persistent storage

volumes:
  mysql_data:
