services:
  # MySQL DB For User Service
  mysql:
    image: mysql:8.0
    container_name: mysql_user_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: user_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - microservices-network

  # MongoDB For Invoice Service
  mongodb:
    image: mongo:4.4
    container_name: mongo_invoice_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: invoice_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - microservices-network

  # RabbitMQ Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    # healthcheck:
    #   test: ["CMD-SHELL", "rabbitmqctl status || exit 1"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 10
    #   start_period: 60s
    networks:
      - microservices-network

  # Gateway Service
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway_service
    restart: always
    ports:
      - "6060:6060"
    # volumes:
    #   - ./gateway:/usr/src/app
    #   - /usr/src/app/node_modules
    environment:
      - ENV=dev
      - PORT=6060
      - SECRET_KEY=supersecret123
      - USER_SERVICE_URL=http://user:6061
      - INVOICE_SERVICE_URL=http://invoice:6062
    depends_on:
      user:
        condition: service_started
      invoice:
        condition: service_started
      audit:
        condition: service_started
      notification:
        condition: service_started
    networks:
      - microservices-network

  # User Service
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user_service
    restart: always
    ports:
      - "6061:6061"
    # volumes:
    #   - ./user:/usr/src/app
    #   - /usr/src/app/node_modules
    environment:
      - ENV=dev
      - PORT=6061
      - DATABASE_URL=mysql://myuser:1234@mysql:3306/user_db
      - SECRET_KEY=supersecret123
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - microservices-network

  # Invoice Service
  invoice:
    build:
      context: ./invoice
      dockerfile: Dockerfile
    container_name: invoice_service
    restart: always
    ports:
      - "6062:6062"
    # volumes:
    #   - ./invoice:/usr/src/app
    #   - /usr/src/app/node_modules
    environment:
      - ENV=dev
      - PORT=6062
      - DATABASE_URL=mongodb://root:1234@mongodb:27017/invoice_db?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - microservices-network

  # # Audit Service
  audit:
    build:
      context: ./audit
      dockerfile: Dockerfile
    container_name: audit_service
    restart: always
    ports:
      - "6063:6063"
    # volumes:
    #   - ./audit:/usr/src/app
    #   - /usr/src/app/node_modules
    environment:
      - ENV=dev
      - PORT=6063
      - DATABASE_URL=mongodb://root:1234@mongodb:27017/audit_db?authSource=admin
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      # rabbitmq:
      #   condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - microservices-network

  # # Notification Service
  notification:
    build:
      context: ./notification
      dockerfile: Dockerfile
    container_name: notification_service
    restart: always
    ports:
      - "6064:6064"
    # volumes:
    #   - ./notification:/usr/src/app
    #   - /usr/src/app/node_modules
    environment:
      - ENV=dev
      - PORT=6064
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - EMAIL_USER=dipakchatterjee956@gmail.com
      - EMAIL_PASS=orxc cgky ajaq clel
    # depends_on:
    #   rabbitmq:
    #     condition: service_healthy
    networks:
      - microservices-network

volumes:
  mysql_data:
  mongo_data:
  rabbitmq_data:

networks:
  microservices-network:
    driver: bridge