services:
  # User Service
  user:
    build: ./user # path to your Dockerfile (inside user folder)
    container_name: user_service
    restart: always
    ports:
      - "6061:6061" # host:container
    env_file:
      - ./user/.env # load environment variables
    depends_on:
      - mysql # wait for MySQL to be up
    environment:
      ENV: dev
      PORT: 6061
      DATABASE_URL: mysql://root:1234@mysql:3306/user_db
    # ^ overrides .env DATABASE_URL at runtime if needed
    networks:
      - app-network
    volumes:
      - ./user:/usr/src/app # Mount local code
      - /usr/src/app/node_modules # Prevent overwriting node_modules

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: mysql_user_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234 # root password
      MYSQL_DATABASE: user_db # auto-create database
      MYSQL_USER: myuser # optional custom user
      MYSQL_PASSWORD: 1234 # user password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql # persistent storage
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
